apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: famous
  template: famous-template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    database-password: ${DATABASE_PASSWORD}
    database-user: ${DATABASE_USER}

- kind: Service
  apiVersion: v1
  metadata:
    name: ${DATABASE_SERVICE_NAME}
  spec:
    selector:
      name: ${DATABASE_SERVICE_NAME}
    ports:
    - name: mysql
      port: 3306
      targetPort: 3306

- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    selector:
      app: ${NAME}
    ports:
    - name: http
      port: 8000
      targetPort: 8000

- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - env:
          - name: DATABASE_SERVICE_NAME
            value: ${DATABASE_SERVICE_NAME}
          - name: DATABASE_NAME
            value: ${DATABASE_NAME}
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${NAME}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${NAME}
          name: ${NAME}
          image: quay.io/netoralves/famous-app
          ports:
          - containerPort: 8000

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the database
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
        name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${NAME}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${NAME}
          - name: MYSQL_DATABASE
            value: ${DATABASE_NAME}
          - name: MYSQL_DEFAULT_AUTHENTICATION_PLUGIN
            value: ${MYSQL_DEFAULT_AUTHENTICATION_PLUGIN}
          image: ' '
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mysql
          ports:
          - containerPort: 3306
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD='${DATABASE_PASSWORD}' mysql -h 127.0.0.1 -u ${DATABASE_USER}
                -D ${DATABASE_NAME} -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: data
        volumes:
        - emptyDir: {}
          name: data
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:${MYSQL_VERSION}
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange


parameters:
- description: 'Nome da aplicacao'
  displayName: Nome
  name: NAME
  required: true
  value: my-app

- description: 'Plugin de autenticacao custom padronizado(default: mysql_native_password)'
  displayName: Plugin de autenticacao MySQL
  name: MYSQL_DEFAULT_AUTHENTICATION_PLUGIN
  value: mysql_native_password

- description: 'Imagem MySQL a ser usada (8.0-el8 or latest).'
  displayName: Versao MySQL
  name: MYSQL_VERSION
  required: true
  value: 8.0-el8

- displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: mysql

- displayName: Nome do Banco de Dados
  name: DATABASE_NAME
  required: true
  value: famousdb

- displayName: Usuario do Banco de Dados
  name: DATABASE_USER
  required: true
  value: dbfamoususer

- displayName: Senha do Banco de Dados
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: DATABASE_PASSWORD

- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: openshift
